apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: empire-secrets
  namespace: empire-engine
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "empire-kv"
    tenantId: ""
    objects: |
      array:
        - |
          objectName: helius-rpc
          objectType: secret
          objectVersion: ""
        - |
          objectName: quicknode-rpc
          objectType: secret
          objectVersion: ""
        - |
          objectName: infura-rpc
          objectType: secret
          objectVersion: ""
        - |
          objectName: solana-private-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: ethereum-private-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgres-conn-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: owner-address-sol
          objectType: secret
          objectVersion: ""
        - |
          objectName: owner-address-eth
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: empire-secrets
      type: Opaque
      data:
        - objectName: helius-rpc
          key: HELIUS_RPC
        - objectName: quicknode-rpc
          key: QUICKNODE_RPC
        - objectName: infura-rpc
          key: INFURA_RPC
        - objectName: solana-private-key
          key: SOLANA_PRIVATE_KEY
        - objectName: ethereum-private-key
          key: ETHEREUM_PRIVATE_KEY
        - objectName: postgres-conn-string
          key: POSTGRES_CONN_STRING
        - objectName: owner-address-sol
          key: OWNER_ADDRESS_SOL
        - objectName: owner-address-eth
          key: OWNER_ADDRESS_ETH